### ISSUE TITLE
Flakiness in TestCreateGazillionTransactionsWhileTransportIsDuplicatingRandomMessages

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#430] opened 2018-11-01 15:17 UTC
https://circleci.com/gh/orbs-network/orbs-network-go/2958?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by electricmonk** [comment] 2018-11-01 17:48
@talkol if this still happens, does this mean that the issue in block storage was not the root cause?

also, log consists (solely) of these messages:
> RUNNING TEST   Start  (test.WithContext hack)

I saw that they were added in a PR you submitted - is this the expected behavior?

**Comment by talkol** [comment] 2018-11-01 18:21
The RUNNING TEST thingie I think we should kill.. It was added to help us debug an issue on CI and it served its purpose (it found block syncs problem).

It's hard to do this hack right for all cases.. it should show the test name but the only good way to do this is to pass `t *testing.T` to all `test.WithContext`s.. but this is a big refactor and not all callers will have access to it.

If we remove this hack, we won't have any way to know which test caused failures that don't print which test failed..

**Comment by talkol** [comment] 2018-11-01 18:22
Duplicate of https://github.com/orbs-network/orbs-network-go/issues/399

**Closed** 2018-11-01 18:22 UTC
Labels: flakiness, high priority
