### ISSUE TITLE
Nil pointer dereference in block sync

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#437] opened 2018-11-01 20:02 UTC
86d5fa2

```
orbs-acceptance_1  | FAIL search snippet: grep _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsDroppingRandomMessages-1541102354-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS test.out
orbs-acceptance_1  | --- FAIL: TestCreateGazillionTransactionsWhileTransportIsDroppingRandomMessages (0.34s)
orbs-acceptance_1  | 	testify_extensions.go:39: Encountered unexpected errors:
orbs-acceptance_1  | 			 recovered panic (passed Error object: goroutine panicked at [github.com/orbs-network/orbs-network-go/services/blockstorage.(*service).sourceHandleBlockAvailabilityRequest:13]: runtime error: invalid memory address or nil pointer dereference)
orbs-acceptance_1  | = RUNNING TEST   Start  (test.WithContext hack)
orbs-acceptance_1  | FAIL
orbs-acceptance_1  | FAIL	github.com/orbs-network/orbs-network-go/test/acceptance	14.735s
```

https://circleci.com/gh/orbs-network/orbs-network-go/3086?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack

**Comment by jlevison** [comment] 2018-11-05 07:36
nope, this is the problem:
```go
	s.logger.Info("received block availability request",
		log.Stringable("petitioner", message.Sender.SenderPublicKey()),
		log.Stringable("requested-first-block", message.SignedBatchRange.FirstBlockHeight()),
		log.Stringable("requested-last-block", message.SignedBatchRange.LastBlockHeight()),
		log.Stringable("requested-last-committed-block", message.SignedBatchRange.LastCommittedBlockHeight()))
```
its in the 'sync server' at `sourceHandleBlockAvailabilityRequest`
it means that sometimes the data from gossip can come uninitialized, either message was null, or something inside it, i'll refactor it later this week, not really sure how to reproduce - need to test the client code and think what can come as null

**Comment by jlevison** [comment] 2018-11-05 11:13
the stack trace for this:
```
runtime/debug.Stack(0xa20b80, 0xc42013cb80, 0xc4206bfa38)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/orbs-network/orbs-network-go/synchronization/supervised.ShortLived.func1.1(0x7fd0b223a538, 0xc420445110)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:28 +0x198
panic(0x9bce40, 0xe84a60)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/orbs-network/orbs-network-go/services/blockstorage.(*service).sourceHandleBlockAvailabilityRequest(0x0, 0xa91780, 0xc42001e180, 0xc42008dd80, 0x1d8, 0x1d9)
	/go/src/github.com/orbs-network/orbs-network-go/services/blockstorage/block_sync_server.go:13 +0x237
github.com/orbs-network/orbs-network-go/services/blockstorage.(*service).HandleBlockAvailabilityRequest(0x0, 0xa91780, 0xc42001e180, 0xc42009a2f8, 0x8cbf3b35b2b40401, 0x8c0000c4206bfdb0, 0x1)
	/go/src/github.com/orbs-network/orbs-network-go/services/blockstorage/service.go:299 +0x4c
github.com/orbs-network/orbs-network-go/services/gossip.(*service).receivedBlockSyncAvailabilityRequest(0xc42030e750, 0xa91780, 0xc42001e180, 0xc4201b8720, 0xc4203b3378, 0x2, 0x2)
	/go/src/github.com/orbs-network/orbs-network-go/services/gossip/topic_block_sync.go:57 +0x306
github.com/orbs-network/orbs-network-go/services/gossip.(*service).receivedBlockSyncMessage(0xc42030e750, 0xa91780, 0xc42001e180, 0xc4201b8720, 0xc4203b3378, 0x2, 0x2)
	/go/src/github.com/orbs-network/orbs-network-go/services/gossip/topic_block_sync.go:20 +0xea
github.com/orbs-network/orbs-network-go/services/gossip.(*service).OnTransportMessageReceived(0xc42030e750, 0xa91780, 0xc42001e180, 0xc4203b3360, 0x3, 0x3)
	/go/src/github.com/orbs-network/orbs-network-go/services/gossip/service.go:58 +0x2ec
github.com/orbs-network/orbs-network-go/test/harness/services/gossip/adapter.(*tamperingTransport).receive(0xc420412a20, 0xa91780, 0xc42001e180, 0xc4203b33b0)
	/go/src/github.com/orbs-network/orbs-network-go/test/harness/services/gossip/adapter/tampering_transport.go:182 +0x18d
github.com/orbs-network/orbs-network-go/test/harness/services/gossip/adapter.(*tamperingTransport).Send.func1()
	/go/src/github.com/orbs-network/orbs-network-go/test/harness/services/gossip/adapter/tampering_transport.go:92 +0x45
github.com/orbs-network/orbs-network-go/synchronization/supervised.ShortLived.func1(0x7fd0b223a538, 0xc420445110, 0xc42025c720)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:31 +0x57
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.ShortLived
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:24 +0x53
```

either `message` or `Sender` or `SignedBatchRange` are nil. The code generating the original request cannot get to the sending part unless it populates some data, so it cannot send a nil value, there is just no logic for that (it may send 'junk' internally, but the object will be there)

the code the receives the request inside gossip also does not seem like it can reach a nil value generation, which is even stranger, its a membuf init that will create the object

what i will do is
1. add unit tests for this code
2. create tests for all nil references
3. add logic that will return an **error** if something comes in nil

then lets hope that when we see the error it will help us understand the issue

**Comment by jlevison** [comment] 2018-11-05 16:09
i'm closing this issue until we see this error again, there is a comment near the logs referencing here

**Comment by danokoch** [comment] 2018-11-06 11:36
with @talkol we decided to undo the local fix here
we believe the solution is a little deeper, the problem is that gossip service is calling the handler when the message is missing some fields
we believe the fix should be in gossip service and not in each of the handlers

**Comment by talkol** [comment] 2018-11-06 18:44
fixed in https://github.com/orbs-network/orbs-network-go/compare/bugfix/block-storage-mutex#diff-ca71e99e32f60b4794f95c27cb462092

**Closed by talkol** 2018-11-06 18:44 UTC
Labels: flakiness

**Comment by itamararjuan** [comment] 2018-11-06 18:54
I think the entire `mutex` + `cpu noise` issues that @talkol  , @danokoch and @jlevison have battled through recently can be a very good spotlight for the next meeting for us to learn on better concurrency habits. I'd love to hear your findings on specific tricky pieces of code in block storage.
