### ISSUE TITLE
Fix flakiness on BlockStorage tests

### ISSUE THREAD

**Issue by IdoZilberberg** [orbs-network/orbs-network-go#379] opened 2018-10-28 16:06 UTC
This has to do with Block Storage test harness.

Error message is:

panic: Mock call missing for:
BroadcastBlockAvailabilityRequest

**Comment by talkol** [comment] 2018-10-28 17:20
Duplicate of https://github.com/orbs-network/orbs-network-go/issues/362

**Comment by electricmonk** [comment] 2018-10-31 09:32
should be fixed in #385 , right, @jlevison?

**Closed by electricmonk** 2018-10-31 09:32 UTC
Labels: flakiness, high priority
