### ISSUE TITLE
benchmark consensus harness should not intantiate global config

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#59] opened 2018-08-01 08:58 UTC
the harness at: services/consensusalgo/benchmarkconsensus/test/harness.go
should not be using the global config directly but rather create a subset of the config thats required by the benchmark config
```go
	config := config.NewHardCodedConfig(
		federationNodes,
		nodePublicKey,
		nodePrivateKey,
		leaderPublicKey,
		consensus.CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS,
		5,
		70,
	)
```

**Comment by talkol** [comment] 2018-08-01 22:16
I agree, I asked @electricmonk what to do and didn't get an answer yet

The only option I see other than instantiating `NewHardCodedConfig` (which is indeed ugly), is copying all the code of `HardCodedConfig` here and creating a duplicate of this class.. If I used 1-2 config params then maybe it would make sense, but I use almost the entirety of the config so copying the whole thing doesn't make sense

We need to improve the config mechanism somehow so instantiating partials is possible

**Comment by electricmonk** [comment] 2018-08-02 04:16
For now just create a local empty struct with getter methods for each of the properties to satisfy the `Config` interface declared by your service. After we have multiple examples for this, if we feel there's massive code duplication, we can try to figure out a better solution. Code generation is one that comes to mind.

**Comment by talkol** [comment] 2018-08-02 07:56
Let's try create instead a hardCoded config that works with mixins

The struct will be divided up to a struct per service and one shared struct

The master hardCoded config will be embedding of all the sub structs

And when I want to create a config in tests I'll create a mixin of the service sub struct and the shared struct

This will avoid all the boilerplate and will be very nice IMO

@electricmonk, you want to play with this or I'll take it?

**Closed** 2018-08-02 11:56 UTC
