### ISSUE TITLE
flakiness in TestGammaCliDeployWithUserDefinedContract

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-network-go#400] opened 2018-10-30 17:35 UTC
see
https://circleci.com/gh/orbs-network/orbs-network-go/2616

**Comment by talkol** [comment] 2018-10-30 18:07
```
--- FAIL: TestGammaCliDeployWithUserDefinedContract (8.68s)
	require.go:201: 
			Error Trace:	gamma_server_and_cli_test.go:220
			            				gamma_server_and_cli_test.go:282
			Error:      	Not equal: 
			            	expected: 0x674
			            	actual  : 0x0
			Test:       	TestGammaCliDeployWithUserDefinedContract
			Messages:   	counter value did not match expected one
```

**Comment by talkol** [comment] 2018-10-30 18:10
it's similar to this open issue: https://github.com/orbs-network/orbs-network-go/issues/370

**Comment by electricmonk** [comment] 2018-10-31 09:28
it's a duplicate of #370 actually

**Comment by electricmonk** [comment] 2018-10-31 13:02
We think that the call to `getCounterValue` reaches the system before `StateStorage` reflects the transaction. (intra-node sync hasn't finished for the block containing the transaction).

Evidence:
transaction for contract with name Counter, method add has tx hash `72582ca45c77eaedabdc804d308b2b36d216932f39f6ec5bbb481fa2f5f290f6`:

```
info 2018-10-29T12:21:17.679423Z adding new transaction to the pool node=dfc06c service=transaction-pool flow=checkpoint transaction={Transaction:{ProtocolVersion:1,VirtualChainId:2a,Timestamp:156213b1fc30b5ab,Signer:{Scheme:(Eddsa){NetworkType:NETWORK_TYPE_TEST_NET,SignerPublicKey:dfc06c5be24a67adee80b35ab4f147bb1a35c55ff85eda69f40ef827bddec173,},},ContractName:Counter,MethodName:add,InputArgumentArray:1400000006000000616d6f756e7401007406000000000000,},Signature:d990551a7b0ab79834b66d634f9fe14355583dfdb313a03979df62780c291c7aabbebfc2faf81793da406b0a86734d989c0389bf26999f6b5f5520bbf97b8800,} txHash=72582ca45c77eaedabdc804d308b2b36d216932f39f6ec5bbb481fa2f5f290f6 function=transactionpool.(*service).AddNewTransaction source=services/transactionpool/add_new_transaction.go:15 
```

transaction with hash `72582ca45c77eaedabdc804d308b2b36d216932f39f6ec5bbb481fa2f5f290f6` entered `block-height=c`

```
info 2018-10-29T12:21:18.260974Z created Results block node=dfc06c service=consensus-context results-block={Header:{ProtocolVersion:1,VirtualChainId:0,BlockHeight:c,PrevBlockHashPtr:0971d9abb23f9ca50132afebae29d755c2afe90306bcb3a0f770bb3d211a2672,Timestamp:0,ReceiptsRootHash:,StateDiffHash:,TransactionsBlockHashPtr:700b5e705393befbb131ddd6ec70bbcbb78fa6877bd450d84dbc0e1f219d1dde,PreExecutionStateRootHash:,TxhashBloomFilter:,TimestampBloomFilter:,NumTransactionReceipts:1,NumContractStateDiffs:2,},TransactionReceipts:[{Txhash:72582ca45c77eaedabdc804d308b2b36d216932f39f6ec5bbb481fa2f5f290f6,ExecutionResult:EXECUTION_RESULT_SUCCESS,OutputArgumentArray:,},],ContractStateDiffs:[{ContractName:Counter,StateDiffs:[{Key:28a9ac8fcae4ef29352b9d446a9168b6249fa0b1,Value:7406000000000000,},],},{ContractName:_Deployments,StateDiffs:[{Key:7febccd5a9db169ba31ba255b5d561e526ca23a9,Value:01000000,},],},],BlockProof:<nil>,} function=consensuscontext.(*service).RequestNewResultsBlock source=services/consensuscontext/service.go:84 
```


Call to `getCounterValue` - State Storage is at `block-height=a`
```
info 2018-10-29T12:21:19.864404Z call method request received via public api node=dfc06c service=public-api flow=checkpoint txHash=a20134b0561516d4a27d7491e4a6c35527cbfae8f8167e077c27a8c01236b52d function=publicapi.(*service).CallMethod source=services/publicapi/run_transaction.go:28 
info 2018-10-29T12:21:19.864421Z running local method node=dfc06c service=virtual-machine contract=Counter method=get block-height=a function=virtualmachine.(*service).RunLocalMethod source=services/virtualmachine/service.go:59 
info 2018-10-29T12:21:19.864477Z processor executing contract node=dfc06c service=processor-native contract=_Deployments method=getInfo function=native.(*service).processMethodCall source=services/processor/native/call.go:57 
info 2018-10-29T12:21:19.864540Z processor executing contract node=dfc06c service=processor-native contract=Counter method=get function=native.(*service).processMethodCall source=services/processor/native/call.go:57 
```

**Comment by talkol** [comment] 2018-10-31 15:13
Awesome! That explains everything. Recap of the flow:

1. User sends transaction to PublicApi.
2. Block is closed by consensus, consensus updates block storage.
3. Block storage updates transaction pool.
4. Transaction pool updates PublicApi and PublicApi updates the user.
5. User calls method on PublicApi.
6. Request arrives to virtual machine which asks state storage for its latest block.
7. PublicApi updates the user.

The race is that there's no guarantee that state storage is updated by the end of step 4. So in step 6 we may get the previous block.

We have 2 different alternatives for mitigation:

### Option 1 - without changing the spec

Step 4 returns the block height where the transaction entered in the receipt.
Step 7 returns the block height of the call method in the response.
If the height in step 7 is lower than step 4, we can just try the call method again.

### Option 2 - with changing the spec

It's easy to prevent this race from happening.
In virtual machine, it currently takes the recent block height from [state storage](https://github.com/orbs-network/orbs-spec/blob/master/behaviors/services/virtual-machine.md#runlocalmethod-method) - see call to `StateStorage.GetStateStorageBlockHeight()`.
We can change this call to be on block storage instead - `BlockStorage.GetStateStorageBlockHeight()`.

I think option 2 is better but we need to get @OdedWx and @erankirsh ok first.

**Comment by electricmonk** [comment] 2018-10-31 20:24
+1 for option 2

**Closed** 2018-11-04 09:45 UTC
Labels: flakiness, high priority
