### ISSUE TITLE
Avoid compilerLock in native_compiler.go

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-network-go#1490] opened 2019-11-28 17:21 UTC
currently in `feature/e2e-to-use-lean-helix` branch and PR #1489 

see todo in line 93:
```
var compilerLock sync.Mutex // workaround to make TestCompileContractConcurrently() pass. TODO resolve without locking
```
test TestCompileContractConcurrently simulates concurrent compilation. when the lock is removed the test gets stuck - compiler process does not start sometimes when another compilation is running

**Comment by vistra** [comment] 2019-12-02 11:20
Couldn't reproduce locally.
I removed the lock in native_compiler.go:95, the test passes after about 10s.
DId I miss anything?

**Comment by ronnno** [comment] 2019-12-02 15:53
On my dev env it failed almost always. if you cant get it to fail in several runs you cannot work on the issue.. return it to me to try and reproduce and if i cant we'll close it

**Comment by noambergIL** [comment] 2020-05-05 09:05
wontfix

**Closed by noambergIL** 2020-05-05 09:05 UTC
Labels: wontfix
