### ISSUE TITLE
Flakiness due to timeout (deadlock?) in acceptance stress tests

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#383] opened 2018-10-28 17:25 UTC
### First type:

https://circleci.com/gh/orbs-network/orbs-network-go/2456?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
--- FAIL: TestCreateGazillionTransactionsWhileTransportIsDelayingRandomMessages (1.04s)
orbs-acceptance_1  | panic: timed out waiting for transaction with hash ac3178c9826cc697d104c0d5f603c7fab18aecd2b1d435dcffd89530d7ae2b77 [recovered]
orbs-acceptance_1  | 	panic: timed out waiting for transaction with hash ac3178c9826cc697d104c0d5f603c7fab18aecd2b1d435dcffd89530d7ae2b77
orbs-acceptance_1  | 
orbs-acceptance_1  | goroutine 12266 [running]:
orbs-acceptance_1  | testing.tRunner.func1(0xc4203c4690)
orbs-acceptance_1  | 	/usr/local/go/src/testing/testing.go:742 +0x29d
orbs-acceptance_1  | panic(0x986b40, 0xc420439240)
orbs-acceptance_1  | 	/usr/local/go/src/runtime/panic.go:502 +0x229
orbs-acceptance_1  | github.com/orbs-network/orbs-network-go/test/harness/services/blockstorage/adapter.(*inMemoryBlockPersistence).WaitForTransaction(0xc420244740, 0xa87480, 0xc420244640, 0xc420b06400, 0x20, 0x20, 0x3b9aca00, 0x20)
orbs-acceptance_1  | 	/go/src/github.com/orbs-network/orbs-network-go/test/harness/services/blockstorage/adapter/memory_persistence.go:57 +0x37f
```

### Second type:

https://circleci.com/gh/orbs-network/orbs-network-go/2475?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
orbs-acceptance_1  | --- FAIL: TestCreateGazillionTransactionsWhileTransportIsDuplicatingRandomMessages (10.29s)
orbs-acceptance_1  | panic: statePersistence.WaitUntilCommittedBlockOfHeight failed: timed out waiting for block at height 4 [recovered]
orbs-acceptance_1  | 	panic: statePersistence.WaitUntilCommittedBlockOfHeight failed: timed out waiting for block at height 4
orbs-acceptance_1  | 
orbs-acceptance_1  | goroutine 17646 [running]:
orbs-acceptance_1  | testing.tRunner.func1(0xc420570ff0)
orbs-acceptance_1  | 	/usr/local/go/src/testing/testing.go:742 +0x29d
orbs-acceptance_1  | panic(0x9879e0, 0xc4202e4d30)
orbs-acceptance_1  | 	/usr/local/go/src/runtime/panic.go:502 +0x229
orbs-acceptance_1  | github.com/orbs-network/orbs-network-go/test/harness.(*inProcessNetwork).WaitForTransactionInStateForAtMost(0xc420335e00, 0xa886c0, 0xc42001e700, 0x2, 0xc42100a0e0, 0x20, 0x20, 0x3b9aca00)
orbs-acceptance_1  | 	/go/src/github.com/orbs-network/orbs-network-go/test/harness/network.go:88 +0x1e7
```

**Comment by talkol** [comment] 2018-10-30 17:32
The first one is probably duplicate of https://github.com/orbs-network/orbs-network-go/issues/383

**Comment by ronnno** [comment] 2018-10-30 17:40
The second one is probably a duplicate of #391, and more specifically the part of it that was fixed.

**Closed** 2018-10-30 18:03 UTC
Labels: flakiness, high priority
